=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'uri'

module SwaggerClient
  class RepositoriesFileVersionsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Delete a repository version
    # Trigger an asynchronous task to delete a repositroy version.
    # @param file_repository_version_href URI of Repository Version. e.g.: /pulp/api/v3/repositories/file/file/1/versions/1/
    # @param [Hash] opts the optional parameters
    # @return [AsyncOperationResponse]
    def delete(file_repository_version_href, opts = {})
      data, _status_code, _headers = delete_with_http_info(file_repository_version_href, opts)
      data
    end

    # Delete a repository version
    # Trigger an asynchronous task to delete a repositroy version.
    # @param file_repository_version_href URI of Repository Version. e.g.: /pulp/api/v3/repositories/file/file/1/versions/1/
    # @param [Hash] opts the optional parameters
    # @return [Array<(AsyncOperationResponse, Fixnum, Hash)>] AsyncOperationResponse data, response status code and response headers
    def delete_with_http_info(file_repository_version_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesFileVersionsApi.delete ...'
      end
      # verify the required parameter 'file_repository_version_href' is set
      if @api_client.config.client_side_validation && file_repository_version_href.nil?
        fail ArgumentError, "Missing the required parameter 'file_repository_version_href' when calling RepositoriesFileVersionsApi.delete"
      end
      # resource path
      local_var_path = '{file_repository_version_href}'.sub('{' + 'file_repository_version_href' + '}', file_repository_version_href.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['Basic']
      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'AsyncOperationResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesFileVersionsApi#delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # List repository versions
    #  FileRepositoryVersion represents a single file repository version.
    # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
    # @param [Hash] opts the optional parameters
    # @option opts [String] :ordering Which field to use when ordering the results.
    # @option opts [Float] :number 
    # @option opts [Float] :number__lt Filter results where number is less than value
    # @option opts [Float] :number__lte Filter results where number is less than or equal to value
    # @option opts [Float] :number__gt Filter results where number is greater than value
    # @option opts [Float] :number__gte Filter results where number is greater than or equal to value
    # @option opts [Float] :number__range Filter results where number is between two comma separated values
    # @option opts [String] :pulp_created__lt Filter results where pulp_created is less than value
    # @option opts [String] :pulp_created__lte Filter results where pulp_created is less than or equal to value
    # @option opts [String] :pulp_created__gt Filter results where pulp_created is greater than value
    # @option opts [String] :pulp_created__gte Filter results where pulp_created is greater than or equal to value
    # @option opts [String] :pulp_created__range Filter results where pulp_created is between two comma separated values
    # @option opts [String] :content Content Unit referenced by HREF
    # @option opts [String] :pulp_created ISO 8601 formatted dates are supported
    # @option opts [Integer] :limit Number of results to return per page.
    # @option opts [Integer] :offset The initial index from which to return the results.
    # @option opts [String] :fields A list of fields to include in the response.
    # @option opts [String] :exclude_fields A list of fields to exclude from the response.
    # @return [InlineResponse20020]
    def list(file_repository_href, opts = {})
      data, _status_code, _headers = list_with_http_info(file_repository_href, opts)
      data
    end

    # List repository versions
    #  FileRepositoryVersion represents a single file repository version.
    # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
    # @param [Hash] opts the optional parameters
    # @option opts [String] :ordering Which field to use when ordering the results.
    # @option opts [Float] :number 
    # @option opts [Float] :number__lt Filter results where number is less than value
    # @option opts [Float] :number__lte Filter results where number is less than or equal to value
    # @option opts [Float] :number__gt Filter results where number is greater than value
    # @option opts [Float] :number__gte Filter results where number is greater than or equal to value
    # @option opts [Float] :number__range Filter results where number is between two comma separated values
    # @option opts [String] :pulp_created__lt Filter results where pulp_created is less than value
    # @option opts [String] :pulp_created__lte Filter results where pulp_created is less than or equal to value
    # @option opts [String] :pulp_created__gt Filter results where pulp_created is greater than value
    # @option opts [String] :pulp_created__gte Filter results where pulp_created is greater than or equal to value
    # @option opts [String] :pulp_created__range Filter results where pulp_created is between two comma separated values
    # @option opts [String] :content Content Unit referenced by HREF
    # @option opts [String] :pulp_created ISO 8601 formatted dates are supported
    # @option opts [Integer] :limit Number of results to return per page.
    # @option opts [Integer] :offset The initial index from which to return the results.
    # @option opts [String] :fields A list of fields to include in the response.
    # @option opts [String] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(InlineResponse20020, Fixnum, Hash)>] InlineResponse20020 data, response status code and response headers
    def list_with_http_info(file_repository_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesFileVersionsApi.list ...'
      end
      # verify the required parameter 'file_repository_href' is set
      if @api_client.config.client_side_validation && file_repository_href.nil?
        fail ArgumentError, "Missing the required parameter 'file_repository_href' when calling RepositoriesFileVersionsApi.list"
      end
      # resource path
      local_var_path = '{file_repository_href}versions/'.sub('{' + 'file_repository_href' + '}', file_repository_href.to_s)

      # query parameters
      query_params = {}
      query_params[:'ordering'] = opts[:'ordering'] if !opts[:'ordering'].nil?
      query_params[:'number'] = opts[:'number'] if !opts[:'number'].nil?
      query_params[:'number__lt'] = opts[:'number__lt'] if !opts[:'number__lt'].nil?
      query_params[:'number__lte'] = opts[:'number__lte'] if !opts[:'number__lte'].nil?
      query_params[:'number__gt'] = opts[:'number__gt'] if !opts[:'number__gt'].nil?
      query_params[:'number__gte'] = opts[:'number__gte'] if !opts[:'number__gte'].nil?
      query_params[:'number__range'] = opts[:'number__range'] if !opts[:'number__range'].nil?
      query_params[:'pulp_created__lt'] = opts[:'pulp_created__lt'] if !opts[:'pulp_created__lt'].nil?
      query_params[:'pulp_created__lte'] = opts[:'pulp_created__lte'] if !opts[:'pulp_created__lte'].nil?
      query_params[:'pulp_created__gt'] = opts[:'pulp_created__gt'] if !opts[:'pulp_created__gt'].nil?
      query_params[:'pulp_created__gte'] = opts[:'pulp_created__gte'] if !opts[:'pulp_created__gte'].nil?
      query_params[:'pulp_created__range'] = opts[:'pulp_created__range'] if !opts[:'pulp_created__range'].nil?
      query_params[:'content'] = opts[:'content'] if !opts[:'content'].nil?
      query_params[:'pulp_created'] = opts[:'pulp_created'] if !opts[:'pulp_created'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'offset'] = opts[:'offset'] if !opts[:'offset'].nil?
      query_params[:'fields'] = opts[:'fields'] if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = opts[:'exclude_fields'] if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['Basic']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'InlineResponse20020')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesFileVersionsApi#list\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
    # Inspect a repository version
    #  FileRepositoryVersion represents a single file repository version.
    # @param file_repository_version_href URI of Repository Version. e.g.: /pulp/api/v3/repositories/file/file/1/versions/1/
    # @param [Hash] opts the optional parameters
    # @option opts [String] :fields A list of fields to include in the response.
    # @option opts [String] :exclude_fields A list of fields to exclude from the response.
    # @return [RepositoryVersion]
    def read(file_repository_version_href, opts = {})
      data, _status_code, _headers = read_with_http_info(file_repository_version_href, opts)
      data
    end

    # Inspect a repository version
    #  FileRepositoryVersion represents a single file repository version.
    # @param file_repository_version_href URI of Repository Version. e.g.: /pulp/api/v3/repositories/file/file/1/versions/1/
    # @param [Hash] opts the optional parameters
    # @option opts [String] :fields A list of fields to include in the response.
    # @option opts [String] :exclude_fields A list of fields to exclude from the response.
    # @return [Array<(RepositoryVersion, Fixnum, Hash)>] RepositoryVersion data, response status code and response headers
    def read_with_http_info(file_repository_version_href, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: RepositoriesFileVersionsApi.read ...'
      end
      # verify the required parameter 'file_repository_version_href' is set
      if @api_client.config.client_side_validation && file_repository_version_href.nil?
        fail ArgumentError, "Missing the required parameter 'file_repository_version_href' when calling RepositoriesFileVersionsApi.read"
      end
      # resource path
      local_var_path = '{file_repository_version_href}'.sub('{' + 'file_repository_version_href' + '}', file_repository_version_href.to_s)

      # query parameters
      query_params = {}
      query_params[:'fields'] = opts[:'fields'] if !opts[:'fields'].nil?
      query_params[:'exclude_fields'] = opts[:'exclude_fields'] if !opts[:'exclude_fields'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['Basic']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'RepositoryVersion')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: RepositoriesFileVersionsApi#read\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
