=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FileExportersFileApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FileExportersFileApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FileExportersFileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FileExportersFileApi' do
    it 'should create an instance of FileExportersFileApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FileExportersFileApi)
    end
  end

  # unit tests for create
  # Create a file file system exporter
  # FileSystemExporters export content from a publication to a path on the file system.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [FileFileFileSystemExporter]
  describe 'create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a file file system exporter
  # FileSystemExporters export content from a publication to a path on the file system.
  # @param file_file_system_exporter_href URI of File File System Exporter. e.g.: /pulp/api/v3/file_exporters/file/file/1/
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for export
  # Trigger an asynchronous task to export a file publication.
  # @param file_file_system_exporter_href URI of File File System Exporter. e.g.: /pulp/api/v3/file_exporters/file/file/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'export test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # List file file system exporters
  # FileSystemExporters export content from a publication to a path on the file system.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [String] :name__in Filter results where name is in a comma-separated list of values
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [InlineResponse20014]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for partial_update
  # Partially update a file file system exporter
  # FileSystemExporters export content from a publication to a path on the file system.
  # @param file_file_system_exporter_href URI of File File System Exporter. e.g.: /pulp/api/v3/file_exporters/file/file/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [FileFileFileSystemExporter]
  describe 'partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for read
  # Inspect a file file system exporter
  # FileSystemExporters export content from a publication to a path on the file system.
  # @param file_file_system_exporter_href URI of File File System Exporter. e.g.: /pulp/api/v3/file_exporters/file/file/1/
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [FileFileFileSystemExporter]
  describe 'read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Update a file file system exporter
  # FileSystemExporters export content from a publication to a path on the file system.
  # @param file_file_system_exporter_href URI of File File System Exporter. e.g.: /pulp/api/v3/file_exporters/file/file/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [FileFileFileSystemExporter]
  describe 'update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
