=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for PulpRpmClient::PublicationsRpmApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PublicationsRpmApi' do
  before do
    # run before each test
    @instance = PulpRpmClient::PublicationsRpmApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PublicationsRpmApi' do
    it 'should create an instance of PublicationsRpmApi' do
      expect(@instance).to be_instance_of(PulpRpmClient::PublicationsRpmApi)
    end
  end

  # unit tests for create
  # Create a rpm publication
  # Trigger an asynchronous task to create a new RPM content publication.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a rpm publication
  # ViewSet for Rpm Publications.
  # @param rpm_publication_href URI of Rpm Publication. e.g.: /pulp/api/v3/publications/rpm/rpm/1/
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # List rpm publications
  # ViewSet for Rpm Publications.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :ordering Which field to use when ordering the results.
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [InlineResponse20016]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for read
  # Inspect a rpm publication
  # ViewSet for Rpm Publications.
  # @param rpm_publication_href URI of Rpm Publication. e.g.: /pulp/api/v3/publications/rpm/rpm/1/
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [RpmRpmPublication]
  describe 'read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
