=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for PulpRpmClient::RepositoriesFileApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RepositoriesFileApi' do
  before do
    # run before each test
    @instance = PulpRpmClient::RepositoriesFileApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RepositoriesFileApi' do
    it 'should create an instance of RepositoriesFileApi' do
      expect(@instance).to be_instance_of(PulpRpmClient::RepositoriesFileApi)
    end
  end

  # unit tests for create
  # Create a file repository
  #  FileRepository represents a single file repository, to which content can be synced, added, or removed.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [FileFileRepository]
  describe 'create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete a file repository
  # Trigger an asynchronous task to delete a repository.
  # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # List file repositorys
  #  FileRepository represents a single file repository, to which content can be synced, added, or removed.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :name 
  # @option opts [String] :name__in Filter results where name is in a comma-separated list of values
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [InlineResponse20019]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for modify
  # Trigger an asynchronous task to create a new repository version.
  # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'modify test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for partial_update
  # Partially update a file repository
  #  FileRepository represents a single file repository, to which content can be synced, added, or removed.
  # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [FileFileRepository]
  describe 'partial_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for read
  # Inspect a file repository
  #  FileRepository represents a single file repository, to which content can be synced, added, or removed.
  # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [FileFileRepository]
  describe 'read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sync
  # Trigger an asynchronous task to sync file content.
  # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'sync test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Update a file repository
  # Trigger an asynchronous task to update a repository.
  # @param file_repository_href URI of File Repository. e.g.: /pulp/api/v3/repositories/file/file/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
