=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::StatusApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatusApi' do
  before do
    # run before each test
    @instance = SwaggerClient::StatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatusApi' do
    it 'should create an instance of StatusApi' do
      expect(@instance).to be_instance_of(SwaggerClient::StatusApi)
    end
  end

  # unit tests for status_read
  # Inspect status of Pulp
  # Returns app information including the version of pulpcore and loaded pulp plugins, known workers, database connection status, and messaging connection status
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [Status]
  describe 'status_read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
