=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::UploadsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UploadsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::UploadsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UploadsApi' do
    it 'should create an instance of UploadsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::UploadsApi)
    end
  end

  # unit tests for commit
  # Finish an Upload
  # Queues a Task that creates an Artifact, and the Upload gets deleted and cannot be re-used.
  # @param upload_href URI of Upload. e.g.: /pulp/api/v3/uploads/1/
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [AsyncOperationResponse]
  describe 'commit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create
  # Create an upload
  # View for chunked uploads.
  # @param data 
  # @param [Hash] opts the optional parameters
  # @return [Upload]
  describe 'create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete
  # Delete an upload
  # View for chunked uploads.
  # @param upload_href URI of Upload. e.g.: /pulp/api/v3/uploads/1/
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # List uploads
  # View for chunked uploads.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :completed ISO 8601 formatted dates are supported
  # @option opts [Integer] :limit Number of results to return per page.
  # @option opts [Integer] :offset The initial index from which to return the results.
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [InlineResponse20023]
  describe 'list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for read
  # Inspect an upload
  # View for chunked uploads.
  # @param upload_href URI of Upload. e.g.: /pulp/api/v3/uploads/1/
  # @param [Hash] opts the optional parameters
  # @option opts [String] :fields A list of fields to include in the response.
  # @option opts [String] :exclude_fields A list of fields to exclude from the response.
  # @return [UploadDetail]
  describe 'read test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update
  # Upload a file chunk
  # Upload a chunk for an upload.
  # @param upload_href URI of Upload. e.g.: /pulp/api/v3/uploads/1/
  # @param file A chunk of the uploaded file.
  # @param content_range The Content-Range header specifies the location of the file chunk within the file.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sha256 The SHA-256 checksum of the chunk if available.
  # @return [Upload]
  describe 'update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
