=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PulpRpmClient::ReservedResources
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReservedResources' do
  before do
    # run before each test
    @instance = PulpRpmClient::ReservedResources.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReservedResources' do
    it 'should create an instance of ReservedResources' do
      expect(@instance).to be_instance_of(PulpRpmClient::ReservedResources)
    end
  end
end
