=begin
#Pulp 3 API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.7

=end

require 'date'

module PulpRpmClient
  class RpmRepoMetadataFile
    attr_accessor :pulp_href

    # Timestamp of creation.
    attr_accessor :pulp_created

    # Artifact file representing the physical content
    attr_accessor :artifact

    # Metadata type.
    attr_accessor :data_type

    # Checksum type for the file.
    attr_accessor :checksum_type

    # Checksum for the file.
    attr_accessor :checksum

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'pulp_href' => :'pulp_href',
        :'pulp_created' => :'pulp_created',
        :'artifact' => :'artifact',
        :'data_type' => :'data_type',
        :'checksum_type' => :'checksum_type',
        :'checksum' => :'checksum'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'pulp_href' => :'String',
        :'pulp_created' => :'DateTime',
        :'artifact' => :'String',
        :'data_type' => :'String',
        :'checksum_type' => :'String',
        :'checksum' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'pulp_href')
        self.pulp_href = attributes[:'pulp_href']
      end

      if attributes.has_key?(:'pulp_created')
        self.pulp_created = attributes[:'pulp_created']
      end

      if attributes.has_key?(:'artifact')
        self.artifact = attributes[:'artifact']
      end

      if attributes.has_key?(:'data_type')
        self.data_type = attributes[:'data_type']
      end

      if attributes.has_key?(:'checksum_type')
        self.checksum_type = attributes[:'checksum_type']
      end

      if attributes.has_key?(:'checksum')
        self.checksum = attributes[:'checksum']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @data_type.nil?
        invalid_properties.push('invalid value for "data_type", data_type cannot be nil.')
      end

      if @data_type.to_s.length < 1
        invalid_properties.push('invalid value for "data_type", the character length must be great than or equal to 1.')
      end

      if @checksum_type.nil?
        invalid_properties.push('invalid value for "checksum_type", checksum_type cannot be nil.')
      end

      if @checksum_type.to_s.length < 1
        invalid_properties.push('invalid value for "checksum_type", the character length must be great than or equal to 1.')
      end

      if @checksum.nil?
        invalid_properties.push('invalid value for "checksum", checksum cannot be nil.')
      end

      if @checksum.to_s.length < 1
        invalid_properties.push('invalid value for "checksum", the character length must be great than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @data_type.nil?
      return false if @data_type.to_s.length < 1
      return false if @checksum_type.nil?
      return false if @checksum_type.to_s.length < 1
      return false if @checksum.nil?
      return false if @checksum.to_s.length < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] data_type Value to be assigned
    def data_type=(data_type)
      if data_type.nil?
        fail ArgumentError, 'data_type cannot be nil'
      end

      if data_type.to_s.length < 1
        fail ArgumentError, 'invalid value for "data_type", the character length must be great than or equal to 1.'
      end

      @data_type = data_type
    end

    # Custom attribute writer method with validation
    # @param [Object] checksum_type Value to be assigned
    def checksum_type=(checksum_type)
      if checksum_type.nil?
        fail ArgumentError, 'checksum_type cannot be nil'
      end

      if checksum_type.to_s.length < 1
        fail ArgumentError, 'invalid value for "checksum_type", the character length must be great than or equal to 1.'
      end

      @checksum_type = checksum_type
    end

    # Custom attribute writer method with validation
    # @param [Object] checksum Value to be assigned
    def checksum=(checksum)
      if checksum.nil?
        fail ArgumentError, 'checksum cannot be nil'
      end

      if checksum.to_s.length < 1
        fail ArgumentError, 'invalid value for "checksum", the character length must be great than or equal to 1.'
      end

      @checksum = checksum
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          pulp_href == o.pulp_href &&
          pulp_created == o.pulp_created &&
          artifact == o.artifact &&
          data_type == o.data_type &&
          checksum_type == o.checksum_type &&
          checksum == o.checksum
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [pulp_href, pulp_created, artifact, data_type, checksum_type, checksum].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = PulpRpmClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
